let listItems = [
    "Face",
    "Skin",
    "Hair",
    "Appliances",
    "Bath & Body",
    "Natural",
    "Mom & Baby",
    "Health & Wellness",
    "Fragnance",
  ];
  
  let data = [
    [
    [
      "Face Primer",
      "Foundation",
      "Compact",
      "Contour",
      "Loose Powder",
      "Tinted Moisturizer",
      "Blush",
      "Bronzer",
      "BB & CC Cream"

    
    ],
      [
        "Eyes",
        "Eyeliner",
        "Mascara",
        "Eye Shadow",
        "Eye Brow Enhancers",
        "Eye Primer",
        "False Eyelashes",
        "Eye Makeup Remover",
        "Under Eye Concealer"

      ],
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
      [
        "Face Brush",
        "Eye Brush",
        "Lip Brush",
        "Brush Sets",
        "Brush Cleaners",
        "Sponges & Applicators",
        "Eyelash Curlers",
        "Tweezers",
      ],
      [
        "Kay Beauty",
        "Huda Beauty",
        "Charlotte Tilbury",
        "M.A.C",
        "Maybelline New York",
        "L'Oreal Paris",
        "Lakme",
        "Nykaa Cosmetics",
       " Nyx Pro.Makeup",
      ],
      [
        "Combos @ Nykaa",
        "New Launches",
       " NFBA Nominees 2022",
       " Gifts @ Nykaa",
        "The Gift Store",
      ],
    ],
    [
      ["Topwear", "Dresses", "Tops", "Sweaters", "Jumpsuits"],
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
      ["Innerwear", "All Innerwear", "Briefs", "Rayonwear"],
      ["Sleepwear", "Nightsuits", "Babysuits"],
      ["Other Ethnic", "All Dupattas", "Lehanga", "Embroidered Wears"],
      
    ],
    [
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
    ],
    [
      ["Top Wear", "View All Wears", "Tshirts", "Shirts"],
      ["Bottom Wear", "Track Pants", "Jeans", "Trousers", "Cotton Tarck"],
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
      ["Inner Wear", "All Innerwear", "Vests ", "Bands"],
    
    ],
    [
      ["Make Up", "All Facewash ", "Eyes", "Lips", "Nails Polish Removers"],
      ["Wellness", "Sanitizers", "Oral Cares", "Medicines", "Powders"],
      ["Covid Essentials", "All Cares", "Thermometer", "Rayon Gun"],
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
      
    ],
    [
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
      ["Kurtis", "All Kurtis", "Anarkali Kurti", "Embroidered Kurtie"],
      ["Other Ethnic", "Blouses", "Ethnic Bottomwear", "Embroidered Ethnic"],
      ["Kurta Sets", "All Kurta Sets", "Kurta Embroidered Kurta"],
    ],
    [
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
      ["Home Decor", "All Clocks", "Anarkali Stickers", "Embroidered Kurtie"],
      ["Stickers", "All Suits & Dress Materials", "Cotton Suits"],
      ["Showpieces", "Blouses", "Ethnic Kitchen", "Embroidered Ethnic"],
      
    ],
    [
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
      ["Infrant 0-2 Years", "Soft Toys", "Footwear", "Stationary", "Watches"],
      ["Boys", "Tshirts", "Cotton Suits", "Watches", "All Devices"],
      ["Girls", "Pins Girls", "Ethnic Toys", "Embroidered Ethnic"],
      
     
    ],
    [
      ["Mobile Accessories", "View All", "All Devices 1"],
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
     
      ["Computers", "All New Computers", "Hars Disks", "Pendrives"],
      ["Laptops", "All Materials", "Mouse", "Keyboard", "All Devices"],
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
    ],
  ];
  
  export { listItems, data };