let listItems = [
    "Face",
    "Skin",
    "Hair",
    "Appliances",
    "Bath & Body",
    "Natural",
    "Mom & Baby",
    "Health & Wellness",
    "Fragnance",
  ];
  
  let data = [
    [
    [
      
      "makeup",
      "skin",
      "hair",
      "appliance",
      "bath&body",
      "natural",
      "mom&baby",
      "health&wellness",
      "men",
      "fragrance",
      "popups",
    
    ],
      [
        "Face Primer",
        "Eye Shadow",
        "Eye Brow Enhancers",
        "Eye Primer",
        "False Eyelashes",
        "Eye Makeup Remover",
        "Under Eye Concealer"

      ],
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
      [
        "Face Brush",
        "Eye Brush",
        "Lip Brush",
        "Brush Sets",
        "Brush Cleaners",
        "Sponges & Applicators",
        "Eyelash Curlers",
        "Tweezers",
      ],
      [
        "Kay Beauty",
        "Huda Beauty",
        "Charlotte Tilbury",
        "M.A.C",
        "Maybelline New York",
        "L'Oreal Paris",
        "Lakme",
        "Nykaa Cosmetics",
       " Nyx Pro.Makeup",
      ],
      [
        "Combos @ Nykaa",
        "New Launches",
       " NFBA Nominees 2022",
       " Gifts @ Nykaa",
        "The Gift Store",
      ],
    ],
    [    [
      
      "makeup",
      "skin",
      "hair",
      "appliance",
      "bath&body",
      "natural",
      "mom&baby",
      "health&wellness",
      "men",
      "fragrance",
      "popups",
    
    ],
      [
        "Face Primer",
        "Eye Shadow",
        "Eye Brow Enhancers",
        "Eye Primer",
        "False Eyelashes",
        "Eye Makeup Remover",
        "Under Eye Concealer"

      ],
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
      [
        "Face Brush",
        "Eye Brush",
        "Lip Brush",
        "Brush Sets",
        "Brush Cleaners",
        "Sponges & Applicators",
        "Eyelash Curlers",
        "Tweezers",
      ],
      [
        "Kay Beauty",
        "Huda Beauty",
        "Charlotte Tilbury",
        "M.A.C",
        "Maybelline New York",
        "L'Oreal Paris",
        "Lakme",
        "Nykaa Cosmetics",
       " Nyx Pro.Makeup",
      ],
      [
        "Combos @ Nykaa",
        "New Launches",
       " NFBA Nominees 2022",
       " Gifts @ Nykaa",
        "The Gift Store",
      ],
    ],
    [    [
      
      "makeup",
      "skin",
      "hair",
      "appliance",
      "bath&body",
      "natural",
      "mom&baby",
      "health&wellness",
      "men",
      "fragrance",
      "popups",
    
    ],
      [
        "Face Primer",
        "Eye Shadow",
        "Eye Brow Enhancers",
        "Eye Primer",
        "False Eyelashes",
        "Eye Makeup Remover",
        "Under Eye Concealer"

      ],
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
      [
        "Face Brush",
        "Eye Brush",
        "Lip Brush",
        "Brush Sets",
        "Brush Cleaners",
        "Sponges & Applicators",
        "Eyelash Curlers",
        "Tweezers",
      ],
      [
        "Kay Beauty",
        "Huda Beauty",
        "Charlotte Tilbury",
        "M.A.C",
        "Maybelline New York",
        "L'Oreal Paris",
        "Lakme",
        "Nykaa Cosmetics",
       " Nyx Pro.Makeup",
      ],
      [
        "Combos @ Nykaa",
        "New Launches",
       " NFBA Nominees 2022",
       " Gifts @ Nykaa",
        "The Gift Store",
      ],
    ],
    [
      [
      
        "makeup",
        "skin",
        "hair",
        "appliance",
        "bath&body",
        "natural",
        "mom&baby",
        "health&wellness",
        "men",
        "fragrance",
        "popups",
      
      ],
        [
          "Face Primer",
          "Eye Shadow",
          "Eye Brow Enhancers",
          "Eye Primer",
          "False Eyelashes",
          "Eye Makeup Remover",
          "Under Eye Concealer"
  
        ],
        [
          "Lips",
          "Lipstick",
          "Liquid Lipstick",
          "Lip Crayon",
          "Lip Gloss",
          "Lip Liner",
          "Lip Plumper",
         " Lip Stain",
        ],
        [
          "Face Brush",
          "Eye Brush",
          "Lip Brush",
          "Brush Sets",
          "Brush Cleaners",
          "Sponges & Applicators",
          "Eyelash Curlers",
          "Tweezers",
        ],
        [
          "Kay Beauty",
          "Huda Beauty",
          "Charlotte Tilbury",
          "M.A.C",
          "Maybelline New York",
          "L'Oreal Paris",
          "Lakme",
          "Nykaa Cosmetics",
         " Nyx Pro.Makeup",
        ],
        [
          "Combos @ Nykaa",
          "New Launches",
         " NFBA Nominees 2022",
         " Gifts @ Nykaa",
          "The Gift Store",
        ],
      ],
    [    [
      
      "makeup",
      "skin",
      "hair",
      "appliance",
      "bath&body",
      "natural",
      "mom&baby",
      "health&wellness",
      "men",
      "fragrance",
      "popups",
    
    ],
      [
        "Face Primer",
        "Eye Shadow",
        "Eye Brow Enhancers",
        "Eye Primer",
        "False Eyelashes",
        "Eye Makeup Remover",
        "Under Eye Concealer"

      ],
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
      [
        "Face Brush",
        "Eye Brush",
        "Lip Brush",
        "Brush Sets",
        "Brush Cleaners",
        "Sponges & Applicators",
        "Eyelash Curlers",
        "Tweezers",
      ],
      [
        "Kay Beauty",
        "Huda Beauty",
        "Charlotte Tilbury",
        "M.A.C",
        "Maybelline New York",
        "L'Oreal Paris",
        "Lakme",
        "Nykaa Cosmetics",
       " Nyx Pro.Makeup",
      ],
      [
        "Combos @ Nykaa",
        "New Launches",
       " NFBA Nominees 2022",
       " Gifts @ Nykaa",
        "The Gift Store",
      ],
    ],
    [
      [
      
        "makeup",
        "skin",
        "hair",
        "appliance",
        "bath&body",
        "natural",
        "mom&baby",
        "health&wellness",
        "men",
        "fragrance",
        "popups",
      
      ],
        [
          "Face Primer",
          "Eye Shadow",
          "Eye Brow Enhancers",
          "Eye Primer",
          "False Eyelashes",
          "Eye Makeup Remover",
          "Under Eye Concealer"
  
        ],
        [
          "Lips",
          "Lipstick",
          "Liquid Lipstick",
          "Lip Crayon",
          "Lip Gloss",
          "Lip Liner",
          "Lip Plumper",
         " Lip Stain",
        ],
        [
          "Face Brush",
          "Eye Brush",
          "Lip Brush",
          "Brush Sets",
          "Brush Cleaners",
          "Sponges & Applicators",
          "Eyelash Curlers",
          "Tweezers",
        ],
        [
          "Kay Beauty",
          "Huda Beauty",
          "Charlotte Tilbury",
          "M.A.C",
          "Maybelline New York",
          "L'Oreal Paris",
          "Lakme",
          "Nykaa Cosmetics",
         " Nyx Pro.Makeup",
        ],
        [
          "Combos @ Nykaa",
          "New Launches",
         " NFBA Nominees 2022",
         " Gifts @ Nykaa",
          "The Gift Store",
        ],
      ],
    [
      [
      
        "makeup",
        "skin",
        "hair",
        "appliance",
        "bath&body",
        "natural",
        "mom&baby",
        "health&wellness",
        "men",
        "fragrance",
        "popups",
      
      ],
        [
          "Face Primer",
          "Eye Shadow",
          "Eye Brow Enhancers",
          "Eye Primer",
          "False Eyelashes",
          "Eye Makeup Remover",
          "Under Eye Concealer"
  
        ],
        [
          "Lips",
          "Lipstick",
          "Liquid Lipstick",
          "Lip Crayon",
          "Lip Gloss",
          "Lip Liner",
          "Lip Plumper",
         " Lip Stain",
        ],
        [
          "Face Brush",
          "Eye Brush",
          "Lip Brush",
          "Brush Sets",
          "Brush Cleaners",
          "Sponges & Applicators",
          "Eyelash Curlers",
          "Tweezers",
        ],
        [
          "Kay Beauty",
          "Huda Beauty",
          "Charlotte Tilbury",
          "M.A.C",
          "Maybelline New York",
          "L'Oreal Paris",
          "Lakme",
          "Nykaa Cosmetics",
         " Nyx Pro.Makeup",
        ],
        [
          "Combos @ Nykaa",
          "New Launches",
         " NFBA Nominees 2022",
         " Gifts @ Nykaa",
          "The Gift Store",
        ],
      ],
    [
      [
      
        "makeup",
        "skin",
        "hair",
        "appliance",
        "bath&body",
        "natural",
        "mom&baby",
        "health&wellness",
        "men",
        "fragrance",
        "popups",
      
      ],
        [
          "Face Primer",
          "Eye Shadow",
          "Eye Brow Enhancers",
          "Eye Primer",
          "False Eyelashes",
          "Eye Makeup Remover",
          "Under Eye Concealer"
  
        ],
        [
          "Lips",
          "Lipstick",
          "Liquid Lipstick",
          "Lip Crayon",
          "Lip Gloss",
          "Lip Liner",
          "Lip Plumper",
         " Lip Stain",
        ],
        [
          "Face Brush",
          "Eye Brush",
          "Lip Brush",
          "Brush Sets",
          "Brush Cleaners",
          "Sponges & Applicators",
          "Eyelash Curlers",
          "Tweezers",
        ],
        [
          "Kay Beauty",
          "Huda Beauty",
          "Charlotte Tilbury",
          "M.A.C",
          "Maybelline New York",
          "L'Oreal Paris",
          "Lakme",
          "Nykaa Cosmetics",
         " Nyx Pro.Makeup",
        ],
        [
          "Combos @ Nykaa",
          "New Launches",
         " NFBA Nominees 2022",
         " Gifts @ Nykaa",
          "The Gift Store",
        ],
      ],
    [    [
      
      "makeup",
      "skin",
      "hair",
      "appliance",
      "bath&body",
      "natural",
      "mom&baby",
      "health&wellness",
      "men",
      "fragrance",
      "popups",
    
    ],
      [
        "Face Primer",
        "Eye Shadow",
        "Eye Brow Enhancers",
        "Eye Primer",
        "False Eyelashes",
        "Eye Makeup Remover",
        "Under Eye Concealer"

      ],
      [
        "Lips",
        "Lipstick",
        "Liquid Lipstick",
        "Lip Crayon",
        "Lip Gloss",
        "Lip Liner",
        "Lip Plumper",
       " Lip Stain",
      ],
      [
        "Face Brush",
        "Eye Brush",
        "Lip Brush",
        "Brush Sets",
        "Brush Cleaners",
        "Sponges & Applicators",
        "Eyelash Curlers",
        "Tweezers",
      ],
      [
        "Kay Beauty",
        "Huda Beauty",
        "Charlotte Tilbury",
        "M.A.C",
        "Maybelline New York",
        "L'Oreal Paris",
        "Lakme",
        "Nykaa Cosmetics",
       " Nyx Pro.Makeup",
      ],
      [
        "Combos @ Nykaa",
        "New Launches",
       " NFBA Nominees 2022",
       " Gifts @ Nykaa",
        "The Gift Store",
      ],
    ],
  ];
  
  export { listItems, data };